import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import NextThemeProvider from "@/provider/NextThemeProvider";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
import { Toaster } from "react-hot-toast";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
      <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
      suppressHydrationWarning
    >
      {/* Add suppressHydrationWarning to the body tag too! */}
      <body className="min-h-full flex flex-col bg-background text-foreground" suppressHydrationWarning>
        <NextThemeProvider attribute="class" defaultTheme="system" enableSystem>
         <Navbar />
         <Toaster
            position="top-center" 
            toastOptions={{
              className: 'bg-white text-emerald-900 border border-emerald-100 shadow-lg',
              success: {
                iconTheme: { primary: '#10b981', secondary: 'white' },
              },
            }}
          />
          <main >{children}</main>
          <Footer />
        </NextThemeProvider>
      </body>
    </html>
  );
}
